### ISSUE TITLE
Website Goals & Value Proposition

### ISSUE THREAD

**Issue by ashleycouperus** [thePlums/web-app#5]
- [ ] What is your app trying to do? 
- [ ] How is it trying to do that? 
- [ ] Why is this problem important to solve?

**Comment by kylemery** [comment]
Collect inspiring thoughts, notes, videos, images, sounds, and everything else all in one place for easy access when working on creative projects.

**Comment by kylemery** [comment]
This app is going to be a funnel for ideas, notes, videos, photos, and other forms of content found in the internet and during the day. On a phone, you can record things or add files to the app for easy access later, or write your own ideas down. On the computer, you can right-click save images and links from the internet, and write your own notes within the app. You can organize these thoughts and files so you can use them later when you're creating something. This problem is important to solve because there are hardly any apps out there like this, and for creatives, it's hard to organize your thoughts. During the day, it's hard to remember your ideas, but with this app you'll be able to record all your thoughts and items from the day.
